<?xml version="1.0" ?>
<robot name="tergeo" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Import  -->
  <xacro:include filename="$(find tergeo_description)/urdf/macro/cfg/cfg_lidar.xacro" ns="lidar" />
  
  <!-- Macro to generate lidar -->
  <xacro:macro name="lidar_model" params="lidar_name parent_link">
    <joint name="${lidar_name}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${lidar_name}_link"/>
      <!-- <origin xyz="-0.032 0 0.172" rpy="0 0 0"/> -->
      <origin xyz="-0.032 0 ${lidar.height+0.172}" rpy="0 0 0"/>
    </joint>
    
    <link name="${lidar_name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://tergeo_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="dark"/>
      </visual>

      <collision>
        <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.0315" radius="0.055"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.0114" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0"
                izz="0.0001" />
      </inertial>
    </link>

    <!-- lidar gazebo ros plugin -->
    <gazebo reference="${lidar_name}_link">
      <material>Gazebo/Red</material>
      <sensor type="ray" name="laser_16">
        <pose>0 0 0 0 0 0</pose>
        <visualize>${lidar.visualize}</visualize>
        <update_rate>${lidar.update_rate}</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>${lidar.h_sample}</samples>
              <resolution>6</resolution>
              <min_angle>${lidar.h_min_angle}</min_angle>
              <max_angle>${lidar.h_max_angle}</max_angle>
            </horizontal>
            <vertical>
              <samples>${lidar.v_sample}</samples>
              <resolution>1</resolution>
              <min_angle>${lidar.v_min_angle}</min_angle>
              <max_angle>${lidar.v_max_angle}</max_angle>
            </vertical>
          </scan>
          <range>
            <min>${lidar.min_range}</min>
            <max>${lidar.max_range}</max>
            <resolution>${lidar.range_res}</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.0</stddev>
          </noise>
        </ray>
        <plugin name="lidar_sensor" filename="libgazebo_ros_velodyne_laser.so">
          <topicName>${lidar.pub_topic_name}</topicName>
          <frameName>${lidar_name}_link</frameName>
          <min_range>${lidar.min_range}</min_range>
          <max_range>${lidar.max_range}</max_range>
          <!-- TODO: Not sure need this arg or not? -->
          <!-- <min_intensity>${min_intensity}</min_intensity> -->
          <gaussianNoise>${lidar.gaussian_noise}</gaussianNoise>
        </plugin>
      </sensor>
    </gazebo>

  </xacro:macro>

</robot>